# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('combo', 'Combo Box'), ('text', 'Text Field'), ('bool', 'Yes or No')], default='bool', max_length=5),
            preserve_default=False,
        ),
    ]
