# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_question_q_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
