# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-18 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20160517_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chebi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(max_length=30)),
                ('name', models.TextField()),
            ],
        ),
    ]
