# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_chebi'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='depends_string',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
