# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_option_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='value',
        ),
        migrations.AddField(
            model_name='answer',
            name='check',
            field=models.CommaSeparatedIntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='yesno',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('combo', 'Combo Box'), ('check', 'Check Boxes'), ('text', 'Text Field'), ('int', 'Integer Field'), ('bool', 'Yes or No')], max_length=5),
        ),
    ]
