# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20160204_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='check',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
