# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20160204_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='number',
            new_name='integer',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='questionnaire.Question'),
        ),
    ]
