# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20160205_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
