# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_question_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('user', 'question')]),
        ),
    ]
