# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_statement'),
    ]

    operations = [
        migrations.CreateModel(
            name='RDFPrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=255)),
            ],
        ),
    ]
