# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_rdfprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='depends_on',
            field=models.ManyToManyField(blank=True, to='questionnaire.Question'),
        ),
    ]
