# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_question_depends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
