# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_category_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdfprefix',
            old_name='prefix',
            new_name='full',
        ),
        migrations.AddField(
            model_name='rdfprefix',
            name='short',
            field=models.CharField(default='fix', max_length=10),
            preserve_default=False,
        ),
    ]
